steps:
  - name: 'python:3.6'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']
  - name: 'gcr.io/$PROJECT_ID/pypi-tools:3.6'
    entrypoint: 'twine'
    args: ['upload', 'dist/*', '-u', '${_PYPI_USERNAME}', '-p', '${_PYPI_PASSWORD}']