steps:
  - name: 'python:3.6'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']
  - name: 'python:3.6'
    entrypoint: /bin/sh
    args: ['twine', 'upload', 'dist/leanbase-1.0.0-py3-none-any.whl']